### ISSUE TITLE
Filter getAllListings not working

### ISSUE THREAD

**Issue by ahmadyusri** [thirdweb-dev/typescript-sdk#255]
I tried to filter listings based on Token ID, but the result still shows Listings from other tokens, is there something wrong with my Code?

Here my code
![Screen Shot 2022-02-11 at 05 05 56](https://user-images.githubusercontent.com/15014011/153504772-04f8a34a-f0b1-4676-af96-bae98c4b509b.png)

Here Log
![Screen Shot 2022-02-11 at 05 06 37](https://user-images.githubusercontent.com/15014011/153504815-88e4058d-efb2-4392-88c5-a4ea6226c915.png)

in my screenshot I filtered by Token ID 1, but the listing on Token ID 0 still appears

**Comment by joaquim-verges** [comment]
sorry for the late reply @ahmadyusri - when filtering by `tokenId`, you also need to pass the `tokenContract` that holds that token (since you can have listings from different contracts).

We're working on providing a better API and documentation on this in our upcoming v2.0 update. Thanks for reporting!
