### ISSUE TITLE
`totalSupply` on `NFTDrop` returns `0`

### ISSUE THREAD

**Issue by NoodleOfDeath** [thirdweb-dev/typescript-sdk#401]
I am using the `useNFTDrop("0xbBf8320D0C65C063a47A9b21605Aa30ed2722b1F")` hook and everything including `claim`, `estimator`, `totalClaimedSupply()`, `totalUnclaimedSupply()` seem to work just fine except for `totalSupply()` which always returns `0` but should return `10000`. I am using `@thirdweb-dev/sdk@2.2.7`. Is this a known issue or do I need to do something else to make `totalSupply()` return the correct value?

**Comment by joaquim-verges** [comment]
hi @NoodleOfDeath - for NFTDrop (and NFTCollection), `totalSupply()` is the amount of NFTs that are actually minted by an end user and currently in circulation. 

So for the case of NFTDrop, NFTs are not "minted by an end user" until they're claimed using `claim()` - That's why we added `totalClaimedSupply()` and `totalUnclaimedSupply()` for NFTDrop to give a clear distinction.

Let me know if that makes sense.

**Comment by NoodleOfDeath** [comment]
Ahh yes that makes more sense. I ended up using `totalClaimedSupply` + `totalUnclaimedSupply` to get my total collection size. I might suggest that `totalSupply` be renamed more precisely like `totalCirculationSupply`?

**Comment by jnsdls** [comment]
hey @NoodleOfDeath, yup that all makes sense.

We're thinking about renaming `totalSupply()` to something like `totalCirculatingSupply()` (name still pending) to make it clearer what it actually does.

For `Edition` `totalSupply` works differently yet again (and we should clarify this as well in the docs, thanks for pointing it out):

- `edition.totalSupply(tokenId)` gives you the amount of that given tokenId that exist
- `edition.getTotalCount()` gives you the size of the edition (aka how many token types exist within the edition)
